name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
       - name: Standard Checkout
         uses: actions/checkout@v2
  
         # Compile notre application
       - name: Build with Maven
         run: mvn --batch-mode --update-snapshots package
